name: Recreated image and push to docker hub

on:
  push:
    branches: [ "developer", "main"]
    
jobs:
  build:

    runs-on: ubuntu-latest


    
    steps:

    - name: Checkoout
      uses: actions/checkout@v4
      
    
    - name: Login docker hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build docker image
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/insurer-api:dev-latest

